### ISSUE TITLE
예약 기능 구현

### ISSUE THREAD

**Issue by SungchoonPark** [PetToYou/PetToYou-BackEnd#82]
# Todo - 예약
## 클라이언트
- [x] 필요한 엔티티 추가 (수의사, 수의사 진료시간, 예약)
- [x] 예약 생성 - 클라이언트 예약
- [ ] 예약 취소 - 클라이언트의 예약 취소
- [ ] 예약 조회 - 클라이언트의 예약 조회
- [ ] 예약 상세조회 - 클라이언트의 예약 조회
- [ ] 현장 QR 예약 기능.

## 병원 관리자
- [x] 예약 생성 - 병원 관리자 타임테이블 추가 
<details><summary>Details</summary>
<p>
reservation과 timeTable 분리, reserve 서비스에 pet, store 등 repository가 의존돼있는거 각 서비스로 분리. 
</p>
</details> 

- [ ] 예약 거부 - 클라이언트의 예약요청을 병원 관리자가 거부
- [ ] 예약 조회 - 병원 관리자의 예약 조회
- [ ] 예약 상세조회 - 병원 관리자의 예약 조회
- [ ] websocket vs long polling vs WebHook 기술 설계
